<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <AcadDir Condition="'$(AcadDir)'==''">C:\Program Files\Autodesk\AutoCAD 2025\</AcadDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="acmgd">
      <HintPath>$(AcadDir)acmgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="acdbmgd">
      <HintPath>$(AcadDir)acdbmgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="accoremgd">
      <HintPath>$(AcadDir)accoremgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
